// img_url-D // decode
javascript:(function(){var urls = [];var links = document.getElementsByTagName('a');for (var i = 0; i < links.length; i++) {var href = decodeURIComponent(links[i].href);var imgUrlIndex = href.indexOf('img_url=');if (imgUrlIndex !== -1) {var imgUrlStartIndex = imgUrlIndex + 8;var imgUrlEndIndex = href.indexOf('&', imgUrlStartIndex);if (imgUrlEndIndex === -1) {imgUrlEndIndex = href.length;}var imgUrlValue = href.substring(imgUrlStartIndex, imgUrlEndIndex);urls.push(imgUrlValue);}}if (urls.length > 0) {var newTab = window.open();newTab.document.write("<html><head><title>Extracted img_url Values" + window.location + "</title></head><body><h1>Extracted img_url Values</h1><h2>" + window.location + "</h2><pre>" + urls.join("\n") + "</pre></body></html>");} else {alert("No URLs containing img_url parameter found on the page.");}})();

// img_url-E // encode
javascript:(function(){var urls = [];var links = document.getElementsByTagName('a');for (var i = 0; i < links.length; i++) {var href = decodeURI(links[i].href);var imgUrlIndex = href.indexOf('img_url=');if (imgUrlIndex !== -1) {var imgUrlStartIndex = imgUrlIndex + 8;var imgUrlEndIndex = href.indexOf('&', imgUrlStartIndex);if (imgUrlEndIndex === -1) {imgUrlEndIndex = href.length;}var imgUrlValue = href.substring(imgUrlStartIndex, imgUrlEndIndex);urls.push(imgUrlValue);}}if (urls.length > 0) {var newTab = window.open();newTab.document.write("<html><head><title>Extracted img_url Values" + window.location + "</title></head><body><h1>Extracted img_url Values</h1><h2>" + window.location + "</h2><pre>" + urls.join("\n") + "</pre></body></html>");} else {alert("No URLs containing img_url parameter found on the page.");}})();

// img_url-Q1 // partial decode + need to trim
javascript:(function(){var urls = [];var links = document.getElementsByTagName('a');for (var i = 0; i < links.length; i++) {var href = decodeURIComponent(links[i].href);var imgUrlIndex = href.indexOf('img_url=');if (imgUrlIndex !== -1) {var imgUrlStartIndex = imgUrlIndex + 8;var imgUrlEndIndex = href.indexOf('"&"', imgUrlStartIndex);if (imgUrlEndIndex === -1) {imgUrlEndIndex = href.length;}var imgUrlValue = href.substring(imgUrlStartIndex, imgUrlEndIndex);urls.push(imgUrlValue);}}if (urls.length > 0) {var newTab = window.open();newTab.document.write("<html><head><title>Extracted img_url Values" + window.location + "</title></head><body><h1>Extracted img_url Values</h1><h2>" + window.location + "</h2><pre>" + urls.join("\n") + "</pre></body></html>");} else {alert("No URLs containing img_url parameter found on the page.");}})();




// img.src
javascript:(function(){var urls=[];document.querySelectorAll('img').forEach(function(img){var url=img.src;if(url){urls.push(url)}});var html='<html><head><title>All URLs on the Page</title></head><body><h1>All URLs on the Page:</h1><ul>';urls.forEach(function(url){html+='<li><a href="'+url+'" target="_blank">'+url+'</a></li>'});html+='</ul></body></html>';var newWindow=window.open();newWindow.document.write(html)})();

// img_url-v1
javascript:(function(){var urls = [];var links = document.getElementsByTagName('a');for (var i = 0; i < links.length; i++) {var href = decodeURIComponent(links[i].href);var imgUrlIndex = href.indexOf('img_url=');if (imgUrlIndex !== -1) {var imgUrlStartIndex = imgUrlIndex + 8;var imgUrlEndIndex = href.indexOf('&', imgUrlStartIndex);if (imgUrlEndIndex === -1) {imgUrlEndIndex = href.length;}var imgUrlValue = href.substring(imgUrlStartIndex, imgUrlEndIndex);urls.push(imgUrlValue);}}if (urls.length > 0) {var newTab = window.open();newTab.document.write("<html><head><title>Extracted img_url Values</title></head><body><h1>Extracted img_url Values</h1><pre>" + urls.join("\n") + "</pre></body></html>");} else {alert("No URLs containing img_url parameter found on the page.");}})();

//img_url-v2
javascript:(function(){var urls = [];var links = document.getElementsByTagName('a');for (var i = 0; i < links.length; i++) {var href = decodeURIComponent(links[i].href);var imgUrlIndex = href.indexOf('img_url=');if (imgUrlIndex !== -1) {var imgUrlStartIndex = imgUrlIndex + 8;var imgUrlEndIndex = href.indexOf('&', imgUrlStartIndex);if (imgUrlEndIndex === -1) {imgUrlEndIndex = href.length;}var imgUrlValue = href.substring(imgUrlStartIndex, imgUrlEndIndex);urls.push(imgUrlValue);}}if (urls.length > 0) {var newTab = window.open();newTab.document.write("<html><head><title>Extracted img_url Values" + window.location + "</title></head><body><h1>Extracted img_url Values</h1><h2>" + window.location + "</h2><pre>" + urls.join("\n") + "</pre></body></html>");} else {alert("No URLs containing img_url parameter found on the page.");}})();




// data-m
javascript:(function(){var urls = [];var links = document.getElementsByTagName('a');for (var i = 0; i < links.length; i++) {var href = decodeURIComponent(links[i].href);var imgUrlIndex = href.indexOf('data-m=');if (imgUrlIndex !== -1) {var imgUrlStartIndex = imgUrlIndex + 8;var imgUrlEndIndex = href.indexOf('&', imgUrlStartIndex);if (imgUrlEndIndex === -1) {imgUrlEndIndex = href.length;}var imgUrlValue = href.substring(imgUrlStartIndex, imgUrlEndIndex);urls.push(imgUrlValue);}}if (urls.length > 0) {var newTab = window.open();newTab.document.write("<html><head><title>Extracted img_url Values</title></head><body><h1>Extracted img_url Values</h1><pre>" + urls.join("\n") + "</pre></body></html>");} else {alert("No URLs containing img_url parameter found on the page.");}})();

//mediaurl
javascript:(function(){var urls = [];var links = document.getElementsByTagName('a');for (var i = 0; i < links.length; i++) {var href = decodeURIComponent(links[i].href);var imgUrlIndex = href.indexOf('mediaurl=');if (imgUrlIndex !== -1) {var imgUrlStartIndex = imgUrlIndex + 8;var imgUrlEndIndex = href.indexOf('&', imgUrlStartIndex);if (imgUrlEndIndex === -1) {imgUrlEndIndex = href.length;}var imgUrlValue = href.substring(imgUrlStartIndex, imgUrlEndIndex);urls.push(imgUrlValue);}}if (urls.length > 0) {var newTab = window.open();newTab.document.write("<html><head><title>Extracted img_url Values</title></head><body><h1>Extracted img_url Values</h1><pre>" + urls.join("\n") + "</pre></body></html>");} else {alert("No URLs containing img_url parameter found on the page.");}})();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
